name: Gradle Package

on:
  pull_request:
    types: [closed]
    branches:
      - 'server/release/*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: server/byob

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: server/byob

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .
      working-directory: server/byob

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: [self-hosted, backend]
    strategy:
      matrix:
        runner: [ip-10-54-0-143, ip-10-54-31-196, ip-172-31-11-94]

    steps:
    - name: docker pull
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

    - name: docker stop container
      run: |
        if [ $(sudo docker ps -a -q -f name=spring-cicd-test) ]; then
          sudo docker stop spring-cicd-test
        fi

    - name: docker run new container
      run: sudo docker run --rm -it -d -p 80:8080 --name spring-cicd-test ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

    - name: delete old docker image
      run: sudo docker system prune -f
