name: Build and Deploy Next.js Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - 'front/release/*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-cicd-test .
      working-directory: front/byob

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-cicd-test

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: [self-hosted, front]
    strategy:
      matrix:
        runner: [ip-10-54-25-112, ip-10-54-5-3, ip-172-31-2-121]
    steps:
    - name: Clean up Docker system before pulling
      run: |
        sudo docker stop $(sudo docker ps -aq) || true
        sudo docker container prune -f || true
        sudo docker image prune -a -f || true
        sudo docker volume prune -f || true
        sudo docker network prune -f || true
        sudo docker system prune -a -f || true

    - name: docker pull
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-cicd-test

    - name: docker run new container
      run: sudo docker run --rm -it -d -p 80:3000 --name nextjs-cicd-test -e SPRING_PRIVATE_DNS_URL=${{ secrets.SPRING_PRIVATE_DNS_URL }} ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-cicd-test

    - name: Clean up unused Docker images after deployment
      run: |
        sudo docker image prune -a -f || true
